//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace LCDMessage.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LCDMessageDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LCDMessageDBEntities object using the connection string found in the 'LCDMessageDBEntities' section of the application configuration file.
        /// </summary>
        public LCDMessageDBEntities() : base("name=LCDMessageDBEntities", "LCDMessageDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LCDMessageDBEntities object.
        /// </summary>
        public LCDMessageDBEntities(string connectionString) : base(connectionString, "LCDMessageDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LCDMessageDBEntities object.
        /// </summary>
        public LCDMessageDBEntities(EntityConnection connection) : base(connection, "LCDMessageDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MessageLog> MessageLogs
        {
            get
            {
                if ((_MessageLogs == null))
                {
                    _MessageLogs = base.CreateObjectSet<MessageLog>("MessageLogs");
                }
                return _MessageLogs;
            }
        }
        private ObjectSet<MessageLog> _MessageLogs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MessageLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessageLogs(MessageLog messageLog)
        {
            base.AddObject("MessageLogs", messageLog);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LCDMessageDBModel", Name="MessageLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MessageLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MessageLog object.
        /// </summary>
        /// <param name="messageID">Initial value of the messageID property.</param>
        /// <param name="message">Initial value of the message property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="messageDate">Initial value of the messageDate property.</param>
        public static MessageLog CreateMessageLog(global::System.Int32 messageID, global::System.String message, global::System.String username, global::System.DateTime messageDate)
        {
            MessageLog messageLog = new MessageLog();
            messageLog.messageID = messageID;
            messageLog.message = message;
            messageLog.username = username;
            messageLog.messageDate = messageDate;
            return messageLog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 messageID
        {
            get
            {
                return _messageID;
            }
            set
            {
                if (_messageID != value)
                {
                    OnmessageIDChanging(value);
                    ReportPropertyChanging("messageID");
                    _messageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("messageID");
                    OnmessageIDChanged();
                }
            }
        }
        private global::System.Int32 _messageID;
        partial void OnmessageIDChanging(global::System.Int32 value);
        partial void OnmessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime messageDate
        {
            get
            {
                return _messageDate;
            }
            set
            {
                OnmessageDateChanging(value);
                ReportPropertyChanging("messageDate");
                _messageDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("messageDate");
                OnmessageDateChanged();
            }
        }
        private global::System.DateTime _messageDate;
        partial void OnmessageDateChanging(global::System.DateTime value);
        partial void OnmessageDateChanged();

        #endregion
    
    }

    #endregion
    
}
